name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Setup environment variables
        run: cp .env.example .env

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Setup database
        run: yarn db:push

      - name: Build web app
        run: yarn build:web
